---
title: "Data Exploration"
author: "Alicia Zhao"
date: "3/31/2020"
output: html_document
---

Upload library packages
```{r}
getwd()
library(tidyverse)
library(lubridate)
library(rvest)
library(scales)
library(cowplot)
```

Upload data for air quality datasets. 
```{r}
# Upload data for NO2. 
NO2.2013 <- read.csv ("../Data/Raw/Air Quality/EPAair_NO2_CA_2013_raw.csv")
NO2.2014 <- read.csv ("../Data/Raw/Air Quality/EPAair_NO2_CA_2014_raw.csv")
NO2.2015 <- read.csv ("../Data/Raw/Air Quality/EPAair_NO2_CA_2015_raw.csv")
NO2.2016 <- read.csv ("../Data/Raw/Air Quality/EPAair_NO2_CA_2016_raw.csv")
NO2.2017 <- read.csv ("../Data/Raw/Air Quality/EPAair_NO2_CA_2017_raw.csv")


# Upload data for O3. 
O3.2013 <- read.csv ("../Data/Raw/Air Quality/EPAair_O3_CA_2013_raw.csv")
O3.2014 <- read.csv ("../Data/Raw/Air Quality/EPAair_O3_CA_2014_raw.csv")
O3.2015 <- read.csv ("../Data/Raw/Air Quality/EPAair_O3_CA_2015_raw.csv")
O3.2016 <- read.csv ("../Data/Raw/Air Quality/EPAair_O3_CA_2016_raw.csv")
O3.2017 <- read.csv ("../Data/Raw/Air Quality/EPAair_O3_CA_2017_raw.csv")


# Upload data for PM2.5. 
PM25.2013 <- read.csv ("../Data/Raw/Air Quality/EPAair_PM25_CA_2013_raw.csv")
PM25.2014 <- read.csv ("../Data/Raw/Air Quality/EPAair_PM25_CA_2014_raw.csv")
PM25.2015 <- read.csv ("../Data/Raw/Air Quality/EPAair_PM25_CA_2015_raw.csv")
PM25.2016 <- read.csv ("../Data/Raw/Air Quality/EPAair_PM25_CA_2016_raw.csv")
PM25.2017 <- read.csv ("../Data/Raw/Air Quality/EPAair_PM25_CA_2017_raw.csv")
```

Combine datasets and save file to repository. Then format data column, explore data. 
```{r}
# Combine pollution datasets by pollutant
NO2.AllYears <- rbind(NO2.2013, NO2.2014, NO2.2015, NO2.2016, NO2.2017)

O3.AllYears<- rbind(O3.2013, O3.2014, O3.2015, O3.2016, O3.2017)

PM25.AllYears<- rbind(PM25.2013, PM25.2014, PM25.2015, PM25.2016, PM25.2017)

# Format data column for NO2 data; Check structure, dimension, summary
NO2.AllYears$Date <- as.Date(NO2.AllYears$Date, format = "%m/%d/%Y")
dim(NO2.AllYears)
str(NO2.AllYears)
summary(NO2.AllYears)

NO2.AllYears$Pollutant <- "NO2"
NO2.Subset <- NO2.AllYears %>%
    select (Date, Site.ID, Daily.Max.1.hour.NO2.Concentration, DAILY_AQI_VALUE, Site.Name, COUNTY,
         COUNTY_CODE, Pollutant) %>%
  mutate (Month = month(Date)) %>%
  mutate (Year = year(Date))
names(NO2.Subset)[3] <- "Concentration"
write.csv(NO2.Subset, row.names = FALSE, 
          file ="../Data/Processed/EPAair_NO2_Processed.csv")

# Format data column for O3 data; Check structure, dimension, summary
O3.AllYears$Date <- as.Date(O3.AllYears$Date, format = "%m/%d/%Y")
dim(O3.AllYears)
str(O3.AllYears)
summary(O3.AllYears)

O3.AllYears$Pollutant <- "O3"
O3.Subset <- O3.AllYears %>%
    select (Date, Site.ID, Daily.Max.8.hour.Ozone.Concentration, DAILY_AQI_VALUE, Site.Name, COUNTY,
         COUNTY_CODE, Pollutant) %>%
  mutate (Month = month(Date)) %>%
  mutate (Year = year(Date))
names(O3.Subset)[3] <- "Concentration"
write.csv(NO2.Subset, row.names = FALSE, 
          file ="../Data/Processed/EPAair_O3_Processed.csv")

# Format data column for PM2.5 data; Check structure, dimension, summary
PM25.AllYears$Date <- as.Date(PM25.AllYears$Date, format = "%m/%d/%Y")
dim(PM25.AllYears)
str(PM25.AllYears)
summary(PM25.AllYears)

PM25.AllYears$Pollutant <- "PM2.5"
PM25.Subset <- PM25.AllYears %>%
  select(Date, Site.ID, Daily.Mean.PM2.5.Concentration, DAILY_AQI_VALUE, Site.Name, COUNTY,
         COUNTY_CODE, Pollutant) %>%
  mutate (Month = month(Date)) %>%
  mutate (Year = year(Date))
names(PM25.Subset)[3] <- "Concentration"

write.csv(PM25.Subset, row.names = FALSE, 
          file ="../Data/Processed/EPAair_PM25_Processed.csv")

# Combine datasets
EPAair <- rbind(NO2.Subset, O3.Subset, PM25.Subset)

```


```{r}
# Visually explore NO2 data
NO2.frequency <- ggplot(subset(EPAair, Pollutant == "NO2")) +
  geom_freqpoly(aes(x = DAILY_AQI_VALUE, color = as.factor(Year)), bins = 50)
print (NO2.frequency)

# Visually explore O3 data
O3.frequency <- ggplot(subset(EPAair, Pollutant == "O3")) +
  geom_freqpoly(aes(x = DAILY_AQI_VALUE, color = as.factor (Year)), bins = 50)
print(O3.frequency)

# Visually explore PM2.5 data
PM25.frequency <- ggplot(subset(EPAair, Pollutant == "PM2.5")) +
  geom_freqpoly(aes(x = DAILY_AQI_VALUE, color = as.factor (Year)), bins = 50)
print(PM25.frequency)

# Visualize data together
Airpollution.frequency <- ggplot(EPAair) +
  geom_freqpoly(aes(x = DAILY_AQI_VALUE, color = Pollutant), bins = 50) +
  labs (y = "Daily AQI Value") + 
  geom_vline(xintercept = 100, lty = 2) 
print(Airpollution.frequency)

Airpollution.boxplot <- ggplot(subset(EPAair, Site.Name %in% c("San Francisco","Bakersfield-California",
                                                  "Los Angeles-North Main Street", "Fresno - Garland")))  +
  geom_boxplot(aes(x = Pollutant, y = DAILY_AQI_VALUE, fill=Site.Name)) +
  labs (x = "", y = "Daily AQI Value", fill = "Site") + 
  geom_hline(yintercept = 100, lty = 2) +
  theme(axis.text.x = element_text(angle = 45,  hjust = 1))
print(Airpollution.boxplot)

```

Upload asthma datasets. 
```{r}
# Upload asthma datasets for adults

Asthma.Adults.2013 <- read.csv ("../Data/Raw/Asthma/TrackingCA_Asthma_ERVisits_Adults_2013_raw.csv")
Asthma.Adults.2014 <- read.csv ("../Data/Raw/Asthma/TrackingCA_Asthma_ERVisits_Adults_2014_raw.csv")
Asthma.Adults.2015 <- read.csv ("../Data/Raw/Asthma/TrackingCA_Asthma_ERVisits_Adults_2015_raw.csv")
Asthma.Adults.2016 <- read.csv ("../Data/Raw/Asthma/TrackingCA_Asthma_ERVisits_Adults_2016_raw.csv")
Asthma.Adults.2017 <- read.csv ("../Data/Raw/Asthma/TrackingCA_Asthma_ERVisits_Adults_2017_raw.csv")

# Upload asthma datasets for children
Asthma.Children.2013 <- read.csv ("../Data/Raw/Asthma/TrackingCA_Asthma_ERVisits_Children_2013_raw.csv")
Asthma.Children.2014 <- read.csv ("../Data/Raw/Asthma/TrackingCA_Asthma_ERVisits_Children_2014_raw.csv")
Asthma.Children.2015 <- read.csv ("../Data/Raw/Asthma/TrackingCA_Asthma_ERVisits_Children_2015_raw.csv")
Asthma.Children.2016 <- read.csv ("../Data/Raw/Asthma/TrackingCA_Asthma_ERVisits_Children_2016_raw.csv")
Asthma.Children.2017 <- read.csv ("../Data/Raw/Asthma/TrackingCA_Asthma_ERVisits_Children_2017_raw.csv")
```

Combine datasets and save file to repository. Then explore data. 
```{r}

# Add year column to all datsets

Asthma.Adults.2013$Year <- 2013
Asthma.Adults.2014$Year <- 2014
Asthma.Adults.2015$Year <- 2015
Asthma.Adults.2016$Year <- 2016
Asthma.Adults.2017$Year <- 2017

Asthma.Children.2013$Year <- 2013
Asthma.Children.2014$Year <- 2014
Asthma.Children.2015$Year <- 2015
Asthma.Children.2016$Year <- 2016
Asthma.Children.2017$Year <- 2017


# Combine adult asthma datasets, save combined file
Asthma.Adults.AllYears <- rbind(Asthma.Adults.2013, Asthma.Adults.2014, Asthma.Adults.2015, Asthma.Adults.2016,Asthma.Adults.2017)
write.csv(Asthma.Adults.AllYears, row.names = FALSE, 
          file ="../Data/Raw/TrackingCA_Asthma_ERVisits_Adults_2013to2017_raw.csv")

# Combine children asthma datasets, save combined file
Asthma.Children.AllYears <- rbind(Asthma.Children.2013, Asthma.Children.2014, Asthma.Children.2015, Asthma.Children.2016,Asthma.Children.2017)
write.csv(Asthma.Children.AllYears, row.names = FALSE, 
          file ="../Data/Raw/TrackingCA_Asthma_ERVisits_Children_2013to2017_raw.csv")

# Explore adult asthma data
dim(Asthma.Adults.AllYears)
str(Asthma.Adults.AllYears)
summary(Asthma.Adults.AllYears)

# Explore children asthma data
dim(Asthma.Children.AllYears)
str(Asthma.Children.AllYears)
summary(Asthma.Children.AllYears)


```
Visually explore datasets. 
```{r}

CA.Asthma <- read.csv("../Data/Processed/TrackingCA_Asthma_AdultsChildren_Processed.csv")
CA.Asthma.gathered <- gather(CA.Asthma, "Age.group", "Incidence", Mean.Incidence.Adults:Mean.Incidence.Children)

# Visually explore adult asthma dataset
adult.asthma.histogram <- ggplot(CA.Asthma) +
  geom_histogram(aes(x = Mean.Incidence.Adults ), bins = 30) +
  scale_x_continuous(limits=c(0, 200))
print(adult.asthma.histogram)

# Visually explore children asthma dataset
children.asthma.histogram <- ggplot(Asthma.Children.AllYears) +
  geom_histogram(aes(x = Incidence ), bins = 30) +
  scale_x_continuous(limits=c(0, 250))
print(children.asthma.histogram)

# Asthma frequency polygon
Asthma.frequency <- ggplot(CA.Asthma.gathered) + 
  geom_freqpoly(aes(x =Incidence, color = Age.group)) + 
  labs ( x = "Asthma-Related ER Visits Per 10,000 People") + 
  scale_color_discrete (name = "Age Group", labels = c("Adults", "Children"))
print (Asthma.frequency)

```

Upload demographics datset
```{r}
Demographics <- read.csv ("../Data/Raw/Demographics/CountyHealthRankings_CA_2019_filtered_raw.csv")

```

Explore demographics dataset
```{r}

dim(Demographics)
str(Demographics)
summary(Demographics)

```

Explore data visually.
```{r}
# Median Household Income
MHI.histogram <- ggplot(Demographics) +
  geom_histogram(aes(x = Median.Household.Income), bins = 15)
print(MHI.histogram)

MHI.frequency <- ggplot(Demographics) +
  geom_freqpoly(aes(x = Median.Household.Income), bins = 15) +
  xlab("Median Household Income")
print(MHI.frequency)

Black.histogram <- ggplot(Demographics) +
  geom_histogram(aes(x = Percent.African.American), bins = 15)
print(Black.histogram)

Black.boxplot<- ggplot(Demographics) +
  geom_boxplot(aes(y = Percent.African.American))
print(Black.boxplot)

Black.freqpoly<- ggplot(Demographics) +
  geom_freqpoly(aes(x = Percent.African.American), bins = 15) +
  xlab("Percent African American")
print(Black.freqpoly)


MHI.boxplot <- ggplot(Demographics) +
  geom_boxplot(aes(y = Median.Household.Income))
print(MHI.boxplot)

Rural.freqpoly<- ggplot(Demographics) +
  geom_freqpoly(aes(x = Percent.Rural), bins = 15) + 
  xlab("Percent Rural")
print(Rural.freqpoly)

Population.freqpoly<- ggplot(Demographics) +
  geom_freqpoly(aes(x = Population), bins = 15) + 
  scale_x_continuous(labels = comma) + 
  
print(Population.freqpoly)

Hispanic.freqpoly<- ggplot(Demographics) +
  geom_freqpoly(aes(x = Percent.Hispanic), bins = 15) + 
  xlab("Percent Hispanic")
print(Hispanic.freqpoly)

# Combine frequency polygrams into one graphic. 
plot_grid(MHI.frequency, Black.freqpoly, Rural.freqpoly, Hispanic.freqpoly, nrow = 2, align = 'h', rel_heights = c(1.25, 1))

```

